<template>
  <div v-loading="loading"><el-button @click="$router.back()" style="margin-bottom:12px">← 返回图谱</el-button><el-card v-if="point"><template #header><b>{{ point.name }}</b></template><el-descriptions :column="1" border><el-descriptions-item label="章节">{{ point.chapter || '-' }}</el-descriptions-item><el-descriptions-item label="说明">{{ point.description || '暂无说明' }}</el-descriptions-item><el-descriptions-item label="前置知识"><el-tag v-for="item in prerequisites" :key="item.knowledgePointId" style="margin-right:6px" @click="$router.push('/knowledge-point/' + item.knowledgePointId)">{{ item.name }}</el-tag><span v-if="!prerequisites.length">无</span></el-descriptions-item><el-descriptions-item label="关联知识"><el-tag v-for="item in relatedPoints" :key="item.knowledgePointId" type="success" style="margin-right:6px" @click="$router.push('/knowledge-point/' + item.knowledgePointId)">{{ item.name }}</el-tag><span v-if="!relatedPoints.length">无</span></el-descriptions-item><el-descriptions-item label="相关资源"><el-link v-for="item in resources" :key="item.resourceId" style="margin-right:8px" type="primary" @click="$router.push('/course-resource/' + item.resourceId + '/preview')">{{ item.title }}</el-link><span v-if="!resources.length">暂无关联资源</span></el-descriptions-item><el-descriptions-item label="关联任务与练习">暂无关联任务与练习（等待模块2、模块3接入知识点关联）</el-descriptions-item></el-descriptions></el-card></div>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { getCourseResources, getKnowledgeGraph, getKnowledgePointDetail, getKnowledgePointPrerequisites } from '../api'
const route = useRoute(); const point = ref(null); const prerequisites = ref([]); const relatedPoints = ref([]); const resources = ref([]); const loading = ref(true)
onMounted(async () => { try { const [detail, pre] = await Promise.all([getKnowledgePointDetail(route.params.knowledgePointId), getKnowledgePointPrerequisites(route.params.knowledgePointId)]); if (detail.data.code === 200) { point.value = detail.data.data; if (pre.data.code === 200) prerequisites.value = pre.data.data; const [graph, resource] = await Promise.all([getKnowledgeGraph(point.value.courseCode), getCourseResources(point.value.courseCode, { knowledgePointId: point.value.knowledgePointId })]); if (resource.data.code === 200) resources.value = resource.data.data; if (graph.data.code === 200) { const byId = Object.fromEntries(graph.data.data.nodes.map(item => [item.knowledgePointId, item])); relatedPoints.value = graph.data.data.edges.filter(edge => edge.relationType === 'related' && (edge.fromKnowledgePointId === point.value.knowledgePointId || edge.toKnowledgePointId === point.value.knowledgePointId)).map(edge => byId[edge.fromKnowledgePointId === point.value.knowledgePointId ? edge.toKnowledgePointId : edge.fromKnowledgePointId]).filter(Boolean) } } } finally { loading.value = false } })
</script>
